# @package _global_

algo:
  _target_: humanoidverse.agents.dagger.dagger.DAgger
  _recursive_: False
  config:
    num_learning_epochs: 5
    num_mini_batches: 4
    clip_param: 0.2
    gamma: 0.99
    lam: 0.95
    value_loss_coef: 1.0
    entropy_coef: 0.008
    learning_rate: 5.e-4 # 5e-4 # 1.e-3
    critic_learning_rate: 1.e-3 # 5e-4 # 1.e-3
    max_grad_norm: 0.2 #1.0
    use_clipped_value_loss: True
    schedule: "adaptive"
    desired_kl: 0.01

    num_steps_per_env: 24
    save_interval: 500

    load_optimizer: True

    init_noise_std: 0.001

    num_learning_iterations: 1000000
    init_at_random_ep_len: True
    eval_callbacks: null

    teacher_ckpt : "/home/irev/ASAP"
    bc_loss_coef : 1.
    module_dict:
      actor: 
        input_dim: [actor_obs]
        output_dim: [robot_action_dim]
        layer_config:
          type: MLP
          hidden_dims: [512, 256, 128]
          activation: ELU
      distill_actor:
        input_dim: [ distill_actor_obs ]
        output_dim: [ robot_action_dim ]
        layer_config:
          type: MLP
          hidden_dims: [ 512, 256, 128 ]
          activation: ELU
      critic: 
        type: MLP
        input_dim: [critic_obs]
        output_dim: [1]
        layer_config:
          type: MLP
          hidden_dims: [512, 256, 128]
          activation: ELU